### ISSUE TITLE
AccessToken可能过期了！请点击“刷新AccessToken”

### ISSUE THREAD

**Issue by Chineseop** [jiyeme/OmenScript#3]
![屏幕截图 2021-07-16 151835](https://user-images.githubusercontent.com/26798571/125908250-2199d711-de08-4dd5-baad-643c72194bbe.png)
之前没更新0.8.3都是好好的！更新0.8.3后就一直这样了，不管怎么重新登录都是这种情况！删除0.8.3脚本后用0.7.18也还是这样，删除cookies重新登录HP也是一样没办法解决，求帮助。

**Comment by Chineseop** [comment]
现在的情况就是不管如何重新登录或者删除新版本脚本重新安装就旧版本也是无法获取SESSION！求大大帮帮忙！

**Comment by jiyeme** [comment]
触发封禁，或被风控，该问题论坛已讨论过。
